"""init1

Revision ID: b10d242036a9
Revises: 31a9cf7aaf4f
Create Date: 2023-01-10 11:13:22.672771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10d242036a9'
down_revision = '31a9cf7aaf4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
